:: Disable devices in Device Manager
DevManView /disable "Motherboard resources"
DevManView /disable "PCI Device"
DevManView /disable "Base System Device"
DevManView /disable "PCI Simple Communications Controller"
DevManView /disable "PCI standard RAM Controller"
DevManView /disable "SM Bus Controller"
DevManView /disable "System timer"
DevManView /disable "High precision event timer"
DevManView /disable "Numeric data processor"
DevManView /disable "Programmable interrupt controller"
DevManView /disable "PCI Data Acquisition and Signal Processing Controller"
DevManView /disable "PCI Encryption/Decryption Controller"
DevManView /disable "NVIDIA USB 3.10 eXtensible Host Controller - 1.10 (Microsoft)"
DevManView /disable "PCI Memory Controller"
DevManView /disable "System board"
DevManView /disable "Microsoft Windows Management Interface for ACPI"