:: enable devices in Device Manager
DevManView /enable "Motherboard resources"
DevManView /enable "PCI Device"
DevManView /enable "Base System Device"
DevManView /enable "PCI Simple Communications Controller"
DevManView /enable "PCI standard RAM Controller"
DevManView /enable "SM Bus Controller"
DevManView /enable "System timer"
DevManView /enable "High precision event timer"
DevManView /enable "Numeric data processor"
DevManView /enable "Programmable interrupt controller"
DevManView /enable "PCI Data Acquisition and Signal Processing Controller"
DevManView /enable "PCI Encryption/Decryption Controller"
DevManView /enable "NVIDIA USB 3.10 eXtensible Host Controller - 1.10 (Microsoft)"
DevManView /enable "PCI Memory Controller"
DevManView /enable "System board"
DevManView /enable "Microsoft Windows Management Interface for ACPI"
DevManView /enable "Intel(R) Power Engine Plug-in"